export enum ROUTES {
    HOME = "/",
    LOGIN = "/login",
    REGISTER = "/register",
    COURSES = "/courses",
    GALLERY = "/gallery",
    SHOP = "/shop",
    ABOUT = "/about",
    NOT_FOUND = "*",
    CONTACT = "/contact",
    ADMIN = "/admin",
    SETTINGS = "/admin/settings",
    PROFILE = "/admin/profile",
    ADD_COURSE = "/admin/add-course",
    CATEGORIES = "/admin/categories",
    ADMIN_COURSES = "/admin/courses",
    USER_DASHBOARD = "/user-dashboard",
    USER_DASHBOARD_COURSES = "/user-dashboard/courses",
}