export enum ROUTES {
    HOME = "/",
    AUTH = "/auth",
    LOGIN = "login",
    REGISTER = "register",
    COURSES = "/courses",
    SINGLE_COURSE = "/courses/:id",
    GALLERY = "/gallery",
    SHOP = "/shop",
    ABOUT = "/about",
    NOT_FOUND = "*",
    CONTACT = "/contact",
    ADMIN = "/admin",
    SETTINGS = "/admin/settings",
    PROFILE = "/admin/profile",
    ADD_COURSE = "/admin/add-course",
    CATEGORIES = "/admin/categories",
    ADMIN_COURSES = "/admin/courses",
    ADMIN_COURSE_SINGLE = "/admin/courses/:id",
    USER_DASHBOARD = "/user-dashboard",
    USER_DASHBOARD_COURSES = "/user-dashboard/courses",
    ADMIN_USERS = "/admin/users",
    ADMIN_GALLERY = "/admin/gallery",
}